// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for suggesting portfolio updates
 * to Dreamcoder08, leveraging user analytics and digital trends to maximize impact and engagement.
 *
 * - suggestPortfolioUpdates - The main function to trigger the portfolio update suggestions flow.
 * - SuggestPortfolioUpdatesInput - The input type for the suggestPortfolioUpdates function.
 * - SuggestPortfolioUpdatesOutput - The output type for the suggestPortfolioUpdates function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPortfolioUpdatesInputSchema = z.object({
  userAnalytics: z.string().describe('A summary of user analytics data for the portfolio, including page views, engagement metrics, and popular content.'),
  digitalTrends: z.string().describe('An overview of current digital trends in cybersecurity, fintech, creative technology, and related fields.'),
  currentPortfolioData: z.string().describe('A summary of the current content and structure of the portfolio.'),
});
export type SuggestPortfolioUpdatesInput = z.infer<typeof SuggestPortfolioUpdatesInputSchema>;

const SuggestPortfolioUpdatesOutputSchema = z.object({
  suggestedUpdates: z.string().describe('A list of suggested updates to the portfolio, including content changes, new sections, and design improvements, based on user analytics and digital trends.'),
  rationale: z.string().describe('The rationale behind each suggested update, explaining how it is expected to improve impact and engagement.'),
});
export type SuggestPortfolioUpdatesOutput = z.infer<typeof SuggestPortfolioUpdatesOutputSchema>;

export async function suggestPortfolioUpdates(input: SuggestPortfolioUpdatesInput): Promise<SuggestPortfolioUpdatesOutput> {
  return suggestPortfolioUpdatesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPortfolioUpdatesPrompt',
  input: {schema: SuggestPortfolioUpdatesInputSchema},
  output: {schema: SuggestPortfolioUpdatesOutputSchema},
  prompt: `You are an AI assistant designed to provide suggestions for updating a professional portfolio to maximize its impact and engagement.

You will receive user analytics data, an overview of current digital trends, and a summary of the current portfolio data.

Based on this information, you will suggest specific updates to the portfolio, explaining how each update is expected to improve impact and engagement.

User Analytics:
{{userAnalytics}}

Digital Trends:
{{digitalTrends}}

Current Portfolio Data:
{{currentPortfolioData}}


Provide a detailed list of suggested updates and a rationale for each suggestion.
Ensure that the suggested updates are practical, actionable, and aligned with the overall goals of maximizing impact and engagement.

Output should be formatted as a list of suggested updates and their rationale.
`,
});

const suggestPortfolioUpdatesFlow = ai.defineFlow(
  {
    name: 'suggestPortfolioUpdatesFlow',
    inputSchema: SuggestPortfolioUpdatesInputSchema,
    outputSchema: SuggestPortfolioUpdatesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
